name: amberframework
version: "0.30.0"
summary: Amber makes building web applications fast, simple, and enjoyable.
description: Amber CLI tool for building web applications in crystal.
base: core
grade: devel
confinement: strict

apps:
  amberframework:
    command: bin/amber

parts:
  amberframework:
    plugin: crystal
    source: .
    source-type: local
    build-packages:
      - git
      - build-essential
      - libreadline-dev
      - libsqlite3-dev
      - libpq-dev
      - libmysqlclient-dev
      - libssl-dev
      - libyaml-dev
